# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-21 13:22
from __future__ import unicode_literals

from django.db import migrations


twitch_emotes = {
    '<3': 0.4,
    '4head': 1,
    'babyrage': -0.7,
    'biblethump': -0.7,
    'blessrng': 0.3,
    'bloodtrail': 0.7,
    'coolstorybob': -1,
    'residentsleeper': -1,
    'kappa': -0.3,
    'lul': -0.3,
    'pogchamp': 1.5,
    'heyguys': 1,
    'wutface': -1.5,
    'kreygasm': 1,
    'seemsgood': 0.7,
    'kappapride': 0.7,
    'feelsgoodman': 1,
    'notlikethis': -1
}


def create_twitch_emotes(apps, schema_editor):
    TwitchEmote = apps.get_model('sentimentBot', 'TwitchEmote')

    for code, positivity in twitch_emotes.items():
        TwitchEmote.objects.get_or_create(word=code, positivity=positivity)


class Migration(migrations.Migration):
    dependencies = [
        ('sentimentBot', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_twitch_emotes)
    ]
